// Mock Receipt Image URL (stable visual placeholder)
export const MOCK_RECEIPT_URL = 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?q=80&w=600&auto=format&fit=crop';

export const INITIAL_CLAIMS = [
  {
    id: 'EXP-2026-101',
    employeeName: 'John Employee',
    title: 'Airtel Broadband Office Link',
    status: 'Submitted', // Submitted/Pending Approval
    amount: 1499,
    invoiceDate: '2026-07-20',
    submissionDate: '2026-07-20T12:00:00Z',
    merchant: 'Airtel Broadband Services',
    invoiceNumber: 'INV-AIR-8821',
    currency: 'INR',
    tax: 228.66,
    category: 'Internet & Communications',
    department: 'Engineering',
    costCenter: 'CC-ENG-402',
    projectCode: 'PROJ-AIR-5G',
    expenseType: 'Reimbursable',
    description: 'Monthly broadband billing for home office connectivity.',
    receiptUrl: MOCK_RECEIPT_URL,
    ocrOverallScore: 94,
    ocrTimestamp: '2026-07-20T12:00:00Z',
    ocrConfidence: { merchant: 98, invoiceNumber: 90, amount: 96, tax: 92, date: 95, category: 94 },
    employeeNotes: 'Charging for broadband allowance.',
    managerComments: '',
    financeComments: '',
  },
  {
    id: 'EXP-2026-102',
    employeeName: 'John Employee',
    title: 'Client Onsite Cab Fare',
    status: 'Reimbursed', // Reimbursed
    amount: 700,
    invoiceDate: '2026-07-18',
    submissionDate: '2026-07-18T16:00:00Z',
    merchant: 'Ola Cabs Fleet',
    invoiceNumber: 'INV-OLA-9923',
    currency: 'INR',
    tax: 35.0,
    category: 'Travel',
    department: 'Sales',
    costCenter: 'CC-SLS-101',
    projectCode: 'PROJ-IND-CLIENT',
    expenseType: 'Reimbursable',
    description: 'Travel from office to client site for project review.',
    receiptUrl: MOCK_RECEIPT_URL,
    ocrOverallScore: 89,
    ocrTimestamp: '2026-07-18T16:00:00Z',
    ocrConfidence: { merchant: 92, invoiceNumber: 85, amount: 95, tax: 80, date: 90, category: 88 },
    employeeNotes: 'Attaching fare invoice.',
    managerComments: 'Approved travel claim.',
    financeComments: 'Ledger settled and paid via corporate account.',
  },
  {
    id: 'EXP-2026-103',
    employeeName: 'John Employee',
    title: 'Partner Engagement Dinner',
    status: 'Returned', // Returned Claim
    amount: 2500,
    invoiceDate: '2026-07-15',
    submissionDate: '2026-07-15T21:30:00Z',
    merchant: 'Taj Buffet Lounge',
    invoiceNumber: 'INV-TAJ-7721',
    currency: 'INR',
    tax: 381.35,
    category: 'Meals',
    department: 'Engineering',
    costCenter: 'CC-ENG-402',
    projectCode: 'PROJ-AIR-5G',
    expenseType: 'Reimbursable',
    description: 'Stakeholder meeting buffet dinner.',
    receiptUrl: MOCK_RECEIPT_URL,
    ocrOverallScore: 74, // Low overall confidence
    ocrTimestamp: '2026-07-15T21:30:00Z',
    ocrConfidence: { merchant: 85, invoiceNumber: 52, amount: 89, tax: 45, date: 91, category: 70 },
    employeeNotes: 'Business meals.',
    managerComments: 'The uploaded receipt document is blurry and missing line items. Please re-upload a clean copy and update the tax allocation.',
    financeComments: '',
  },
  {
    id: 'EXP-2026-104',
    employeeName: 'Jane Dev',
    title: 'IDE Tool License Annual',
    status: 'Submitted', // Submitted/Pending Approval
    amount: 3701,
    invoiceDate: '2026-07-19',
    submissionDate: '2026-07-19T10:15:00Z',
    merchant: 'JetBrains s.r.o.',
    invoiceNumber: 'INV-JB-55612',
    currency: 'INR',
    tax: 564.55,
    category: 'Software Licences',
    department: 'Engineering',
    costCenter: 'CC-ENG-402',
    projectCode: 'PROJ-AIR-5G',
    expenseType: 'Reimbursable',
    description: 'Personal subscription renewal for IntelliJ Ultimate IDE.',
    receiptUrl: MOCK_RECEIPT_URL,
    ocrOverallScore: 78,
    ocrTimestamp: '2026-07-19T10:15:00Z',
    ocrConfidence: { merchant: 85, invoiceNumber: 74, amount: 92, tax: 68, date: 88, category: 70 },
    employeeNotes: 'Requesting subscription allowance.',
    managerComments: '',
    financeComments: '',
  },
  {
    id: 'EXP-2026-105',
    employeeName: 'Sam Finance',
    title: 'Testing Mobile handset',
    status: 'Approved', // Approved (Awaiting payment)
    amount: 15400,
    invoiceDate: '2026-07-15',
    submissionDate: '2026-07-15T11:00:00Z',
    merchant: 'Airtel Corporate Store',
    invoiceNumber: 'INV-ART-4412',
    currency: 'INR',
    tax: 2349.15,
    category: 'Hardware Purchase',
    department: 'Finance',
    costCenter: 'CC-FIN-102',
    projectCode: 'PROJ-CORE-INFRA',
    expenseType: 'Corporate Card',
    description: 'Test devices for network quality audits.',
    receiptUrl: MOCK_RECEIPT_URL,
    ocrOverallScore: 97,
    ocrTimestamp: '2026-07-15T11:00:00Z',
    ocrConfidence: { merchant: 99, invoiceNumber: 95, amount: 98, tax: 96, date: 98, category: 97 },
    employeeNotes: 'Approved budget purchase.',
    managerComments: 'Approved.',
    financeComments: '',
  },
  {
    id: 'EXP-2026-106',
    employeeName: 'John Employee',
    title: 'Cloud Server Sandbox hosting',
    status: 'Draft', // Draft
    amount: 1000,
    invoiceDate: '2026-07-10',
    submissionDate: '2026-07-10T10:00:00Z',
    merchant: 'Amazon Web Services',
    invoiceNumber: 'INV-AWS-8812',
    currency: 'INR',
    tax: 152.54,
    category: 'Software Licences',
    department: 'Engineering',
    costCenter: 'CC-ENG-402',
    projectCode: 'PROJ-AIR-5G',
    expenseType: 'Reimbursable',
    description: 'Developer sandbox servers charges.',
    receiptUrl: MOCK_RECEIPT_URL,
    ocrOverallScore: 95,
    ocrTimestamp: '2026-07-10T10:00:00Z',
    ocrConfidence: { merchant: 99, invoiceNumber: 92, amount: 98, tax: 95, date: 97, category: 96 },
    employeeNotes: 'Developer draft details.',
    managerComments: '',
    financeComments: '',
  }
];
